version: "3.5"

services:
  db80:
     network_mode: host
     image: mysql:8.0
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
     volumes:
       - ./packages/nocodb/tests/mysql-sakila-db:/docker-entrypoint-initdb.d
  xc-cypress-nocodb:
    network_mode: host
    image: node:12.22.1-slim
    volumes:
      - ./packages/nocodb:/home/app
    command:
      - /bin/bash
      - -c
      - |
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        cd /home/app/ && rm package-lock.json && npm i && npm run run
  xc-cypress-nc-gui:
    network_mode: host
    image: node:12.22.1-slim
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./packages/nc-gui:/home/app
      - ./packages/nc-lib-gui:/home/nc-lib-gui
    command:
      - /bin/bash
      - -c
      - |
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        cd /home/app/ && rm package-lock.json && npm i && npm run dev
